name: testing_and_coverage

on:
  push:
    branches: [main]

jobs:
  testing_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv lock --locked
      - run: uv sync --all-groups
      - run: uv run pytest --cov=project -v